// Generated by gencpp from file servo_node/ServoMsg.msg
// DO NOT EDIT!


#ifndef SERVO_NODE_MESSAGE_SERVOMSG_H
#define SERVO_NODE_MESSAGE_SERVOMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_node
{
template <class ContainerAllocator>
struct ServoMsg_
{
  typedef ServoMsg_<ContainerAllocator> Type;

  ServoMsg_()
    : ID(0)
    , TIME(0)
    , position(0)  {
    }
  ServoMsg_(const ContainerAllocator& _alloc)
    : ID(0)
    , TIME(0)
    , position(0)  {
  (void)_alloc;
    }



   typedef int32_t _ID_type;
  _ID_type ID;

   typedef int32_t _TIME_type;
  _TIME_type TIME;

   typedef int32_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::servo_node::ServoMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_node::ServoMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ServoMsg_

typedef ::servo_node::ServoMsg_<std::allocator<void> > ServoMsg;

typedef boost::shared_ptr< ::servo_node::ServoMsg > ServoMsgPtr;
typedef boost::shared_ptr< ::servo_node::ServoMsg const> ServoMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_node::ServoMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_node::ServoMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servo_node::ServoMsg_<ContainerAllocator1> & lhs, const ::servo_node::ServoMsg_<ContainerAllocator2> & rhs)
{
  return lhs.ID == rhs.ID &&
    lhs.TIME == rhs.TIME &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servo_node::ServoMsg_<ContainerAllocator1> & lhs, const ::servo_node::ServoMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servo_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::servo_node::ServoMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_node::ServoMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_node::ServoMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_node::ServoMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_node::ServoMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_node::ServoMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_node::ServoMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c895e7425808012a7d34d41c08e79017";
  }

  static const char* value(const ::servo_node::ServoMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc895e7425808012aULL;
  static const uint64_t static_value2 = 0x7d34d41c08e79017ULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_node::ServoMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_node/ServoMsg";
  }

  static const char* value(const ::servo_node::ServoMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_node::ServoMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32   ID\n"
"int32 TIME\n"
"int32 position\n"
;
  }

  static const char* value(const ::servo_node::ServoMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_node::ServoMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.TIME);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_node::ServoMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_node::ServoMsg_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ID);
    s << indent << "TIME: ";
    Printer<int32_t>::stream(s, indent + "  ", v.TIME);
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_NODE_MESSAGE_SERVOMSG_H
